export const JOB_BOARD_REQUEST = "JOB_BOARD_REQUEST"
export const JOB_BOARD_SUCCESS = "JOB_BOARD_SUCCESS"
export const JOB_BOARD_FAIL = "JOB_BOARD_FAIL"

export const JOB_BOARD_APPLY_REQUEST = "JOB_BOARD_APPLY_REQUEST"
export const JOB_BOARD_APPLY_SUCCESS = "JOB_BOARD_APPLY_SUCCESS"
export const JOB_BOARD_APPLY_FAIL = "JOB_BOARD_APPLY_FAIL"
